# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~


    filter_sets:
        # use the default cache configuration
        cache: ~

        thumb_200:
            quality: 75
            filters:
                thumbnail:
                    size: [ 200, 200 ]
                    mode: 'inset'

        thumb_300:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: 'inset'

        medium_400:
            quality: 75
            filters:
                thumbnail:
                    size: [ 500, 500 ]
                    mode: 'inset'

        medium_500:
            quality: 75
            filters:
                thumbnail:
                    size: [ 500, 500 ]
                    mode: 'inset'

        masonry_thumb:
            quality: 75
            filters:
                relative_resize:
                    widen: 300


